backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  # These lines should *not* be indented
media_folder: "_site/images/uploads"
public_folder: "/images/uploads"